/**
 * The launcher for clients that cannot run the engine via `npx` themselves —
 * Claude Desktop today, and Antigravity (see antigravity.ts), which reuses this
 * file verbatim. Nothing in it is Desktop-specific; the name is historical.
 *
 * Claude Desktop has no plugin marketplace and no
 * `${user_config}` interpolation, so — unlike Claude Code, whose plugin runs
 * the engine via a pinned `npx @cognigy/plugin-engine@<version> cognigy-mcp`
 * command — Desktop needs a launcher that decides on its own when to pull a new
 * engine. This launcher is a LOCAL file written to ~/.cognigy-plugin/ (not a
 * marketplace-distributed plugin file), so it is not subject to Desktop's
 * server-side plugin scan and may safely npm-install + spawn at boot.
 *
 * This module owns the launcher's SOURCE (written verbatim to
 * ~/.cognigy-plugin/desktop-launch.mjs by the installer) and a writer for it.
 * The launcher path is stable across engine bumps because it lives outside the
 * versioned engine dir; launcher-code fixes ship via an installer re-run.
 *
 * Launcher behaviour, every boot (no throttle — Desktop spawns the server once
 * per app launch, so always-latest beats a ~1-2s boot delay, and nothing talks
 * to the server in that window):
 *   1. Probe the npm registry for @latest (bounded timeout — a dead network must
 *      not hang Desktop boot).
 *   2. If newer than the installed engine, `npm install` it BEFORE handing off,
 *      so the new version is live the same boot.
 *   3. Re-stage the Antigravity plugin's skills/agents when the engine moved
 *      (no-op for Desktop, which has no plugin dir). Antigravity ships no
 *      update command, no marketplace and no refresh of its own — see
 *      antigravity.ts — so plugin files only track the engine if we do it here.
 *   4. Hand off by importing the engine's dist/index.js (which self-invokes
 *      main() and connects the MCP stdio transport).
 *   5. Offline-safe: if the probe/install fails or times out but an engine is
 *      already on disk, boot it and warn on stderr. Hard-fail only when no engine
 *      exists at all (first-ever boot while offline).
 *
 * npm is resolved from the running node (process.execPath), never from PATH:
 * Desktop launches the server with a minimal PATH, and invoking `node npm-cli.js`
 * also sidesteps the Windows npm.cmd + CVE-2024-27980 spawn issue.
 *
 * stdout is reserved for the MCP stdio transport (JSON-RPC) — every diagnostic
 * goes to stderr and npm's stdout is dropped.
 */
import { chmodSync, mkdirSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";

export const USER_HOME_DIR = join(homedir(), ".cognigy-plugin");
export const DESKTOP_LAUNCHER_FILE = join(USER_HOME_DIR, "desktop-launch.mjs");

export const DESKTOP_LAUNCHER_SOURCE = `// Cognigy engine launcher — auto-updates the engine on every boot, then hands off.
// Generated by \`cognigy-setup\`. Do not edit; re-run the installer to refresh.
// stdout is reserved for the MCP stdio transport (JSON-RPC); all diagnostics -> stderr.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

const PKG = "@cognigy/plugin-engine";
const ROOT = join(homedir(), ".cognigy-plugin", "engine");
const engineDir = join(ROOT, "node_modules", "@cognigy", "plugin-engine");
const engineEntry = join(engineDir, "dist", "index.js");
const enginePkg = join(engineDir, "package.json");
const PROBE_TIMEOUT_MS = 15000;
const INSTALL_TIMEOUT_MS = 120000;
const isWin = process.platform === "win32";

function note(m) {
  process.stderr.write(\`[cognigy] \${m}\\n\`);
}

function installedVersion() {
  try {
    return JSON.parse(readFileSync(enginePkg, "utf8")).version;
  } catch {
    return null;
  }
}

// npm ships alongside node; resolve npm-cli.js from the running node so we don't
// depend on PATH (Desktop launches with a minimal PATH) and can invoke it via
// \`node npm-cli.js\` — sidestepping the Windows npm.cmd + CVE-2024-27980 issue.
function resolveNpmCli() {
  const nodeDir = dirname(process.execPath);
  const candidates = [
    join(nodeDir, "node_modules", "npm", "bin", "npm-cli.js"),
    join(nodeDir, "..", "lib", "node_modules", "npm", "bin", "npm-cli.js"),
  ];
  for (const c of candidates) if (existsSync(c)) return c;
  return null;
}

const npmCli = resolveNpmCli();

function npm(args, timeout, capture) {
  const stdio = capture
    ? ["ignore", "pipe", "pipe"]
    : ["ignore", "ignore", "inherit"];
  if (npmCli) {
    return spawnSync(process.execPath, [npmCli, ...args], {
      encoding: "utf8",
      timeout,
      stdio,
    });
  }
  // Fallback: npm on PATH. On Windows it's npm.cmd, which needs shell:true and
  // manual quoting since Node's CVE-2024-27980 fix refuses to spawn .cmd
  // otherwise. Quote every arg so cmd metacharacters stay literal.
  const bin = isWin ? "npm.cmd" : "npm";
  const finalArgs = isWin
    ? args.map((a) => \`"\${a.replace(/"/g, '\\\\"')}"\`)
    : args;
  return spawnSync(bin, finalArgs, { encoding: "utf8", timeout, shell: isWin, stdio });
}

function latestVersion() {
  const res = npm(["view", \`\${PKG}@latest\`, "version"], PROBE_TIMEOUT_MS, true);
  if (res.status !== 0 || !res.stdout) return null;
  return res.stdout.trim() || null;
}

function install(version) {
  const res = npm(
    ["install", \`\${PKG}@\${version}\`, "--prefix", ROOT, "--no-fund", "--no-audit", "--loglevel=error"],
    INSTALL_TIMEOUT_MS,
    false,
  );
  return res.status === 0 && !res.error;
}

const current = installedVersion();
const latest = latestVersion();
if (latest && latest !== current) {
  note(\`updating engine \${current ?? "none"} -> \${latest}\`);
  if (!install(latest)) note(\`update failed; continuing with \${current ?? "none"}.\`);
} else if (!latest) {
  note(\`registry unreachable; continuing with installed engine \${current ?? "none"}.\`);
}

if (!existsSync(engineEntry)) {
  note(\`no engine present at \${engineEntry} and the registry is unreachable.\`);
  note(\`connect to a network and restart your client, or re-run: npx -y -p \${PKG}@latest cognigy-setup\`);
  process.exit(1);
}

// Antigravity keeps skills and agents as plain files inside its plugin dir and
// has no update command, marketplace, or refresh of its own, so they only track
// the engine if we re-stage them. Version-gated: this runs once per release, not
// every boot. A no-op wherever no Cognigy plugin dir exists (Claude Desktop).
async function syncAntigravityPlugin() {
  try {
    const mod = await import(
      pathToFileURL(join(engineDir, "dist", "install", "antigravity.js")).href
    );
    if (!mod.antigravityHasPlugin?.()) return;
    const staged = mod.installedPluginVersion?.() ?? null;
    const engine = installedVersion();
    if (!engine || staged === engine) return;
    mod.updateAntigravity();
    note(\`refreshed Antigravity skills/agents \${staged ?? "none"} -> \${engine}; restart Antigravity to load them\`);
  } catch (err) {
    note(\`could not refresh Antigravity plugin files: \${err?.message ?? err}\`);
  }
}
await syncAntigravityPlugin();

await import(pathToFileURL(engineEntry).href);
`;

/**
 * Write the Desktop launcher to ~/.cognigy-plugin/desktop-launch.mjs (dir 0700).
 * Returns the launcher path.
 */
export function writeDesktopLauncher(dir: string = USER_HOME_DIR): string {
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  chmodSync(dir, 0o700);
  const file = join(dir, "desktop-launch.mjs");
  writeFileSync(file, DESKTOP_LAUNCHER_SOURCE, { mode: 0o600 });
  chmodSync(file, 0o600);
  return file;
}
